title: openvidu.io
email: openvidu@gmail.com
description: OpenVidu platform
baseurl: "/"
url: "https://openvidu.io"
twitter_username: openvidu

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  auto_ids: true
