FROM squidfunk/mkdocs-material:9.7.0
RUN pip install mkdocs-glightbox mkdocs-llmstxt
RUN pip install mike
RUN mike deploy
ENTRYPOINT ["/sbin/tini", "--", "mike"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]