"""MkDocs hook: exposes ovweb.yaml to the templates, and makes llms.txt and the sitemap true.

Wired up through `hooks:` in mkdocs.yml. Three jobs, all of them about keeping one fact in one
place:

* `on_config` publishes the layout and the redirect patterns on `config.extra.ovweb`, so the
  404 router (docs/overrides/404.html) compiles them from the same configuration ovweb
  publishes with instead of hardcoding a list that has to be kept in sync by hand.
* `on_env` sets each page's `update_date` from git, so `sitemap.xml` carries a real per-page
  `<lastmod>` instead of the build date on every URL.
* `on_page_content` gives the `llmstxt` plugin each page's own `title` and `description`
  frontmatter, so its llms.txt entry is the name and the sentence written on the page.

The import shim below keeps a plain `mkdocs serve` working in a checkout where the package is
not installed — including inside the Docker images, which mount the repository rather than
installing anything. It does not duplicate any logic: the config loader, the pattern expansion
and the source-date rules have exactly one implementation, in `ovweb`.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

from mkdocs.exceptions import PluginError

_SRC = Path(__file__).resolve().parent / "src"
if _SRC.is_dir() and str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from ovweb.config import load_site_config  # noqa: E402
from ovweb.gitrepo import Git, GitError  # noqa: E402
from ovweb.redirects import resolve_patterns  # noqa: E402
from ovweb.sources import newest_dates, parse_git_log  # noqa: E402

#: Anything the sitemap dates can be read out of lives under one of these, relative to the
#: repository root: the pages themselves, and the snippets they include.
_DATED_TREES = ("docs", "shared")

_log = logging.getLogger(f"mkdocs.hooks.{Path(__file__).stem}")


def on_config(config, **kwargs):
    """Publish the layout and the 404 redirect patterns on `config.extra.ovweb`.

    ovweb sets `$OVWEB_SITE_CONFIG` when it invokes mike, so a publish build and the
    post-processing that follows it always read the same file — which matters for a past
    version, whose branch carries its own stale copy of ovweb.yaml.
    """
    site_config = load_site_config()
    config["extra"]["ovweb"] = {
        "versioned_pages": list(site_config.layout.versioned_pages),
        "non_versioned_pages": list(site_config.layout.non_versioned_pages),
        "redirect_patterns": [
            {"id": pattern.id, "match": pattern.match, "to": pattern.to}
            for pattern in resolve_patterns(site_config)
        ],
    }
    return config


def _source_dates(root: Path) -> dict[str, str] | None:
    """`{repository-relative path: date of its last commit}`, or None when git cannot answer.

    Returning None means "leave MkDocs' build date alone". Three ordinary situations reach it,
    and none of them may fail the build: a shallow clone (`validate-web.yaml` checks out at the
    default depth, where `git log` succeeds but reports the fetched commit for every path — wrong
    data, which is worse than no data), no git binary, and git refusing a repository whose files
    belong to another user, which is what happens inside the Docker images because they mount the
    working copy from the host.

    Logged at INFO on purpose: `mkdocs build --strict` fails on a WARNING, so warning here would
    break every PR's validation build.
    """
    git = Git(root)
    try:
        if git.is_shallow():
            _log.info("Shallow clone: sitemap <lastmod> falls back to the build date.")
            return None
        return parse_git_log(git.log_dates_for(*_DATED_TREES))
    except (GitError, OSError) as error:
        _log.info(
            "Could not read dates from git (%s): <lastmod> falls back to the build date.", error
        )
        return None


def on_env(env, config, files, **kwargs):
    """Give each page a real `update_date`, which is what `sitemap.xml` publishes as `<lastmod>`.

    MkDocs sets `update_date` to the build date for every page, so the sitemap asserted that all
    261 URLs changed on every publish. A date computed from the page's sources is both true and
    useful: it lets a crawler tell an edited page from an untouched one, and it stops the file
    churning on publishes that changed nothing.

    `on_env` is the only hook that can do this. MkDocs renders the theme's static templates —
    `sitemap.xml` among them — *before* it renders the pages, so `on_page_content` and
    `on_page_context` both run too late. Here every `file.page` already exists, and the work
    happens once rather than once per page.

    Pages generated by a plugin (the blog's archive, category and pagination views) have no source
    file to date, so they get **no** `<lastmod>` rather than an invented one: `update_date = ""` is
    falsy, and the sitemap template omits the element. The sitemap spec makes the field optional
    per URL.
    """
    # `docs/` and `shared/` are named relative to the project root, which is also the repository
    # root here, and is what pymdownx.snippets resolves an include against.
    docs_dir = Path(config["docs_dir"]).resolve()
    root = docs_dir.parent

    pages, generated = {}, 0
    for file in files.documentation_pages():
        if file.page is None:
            continue
        if file.generated_by is not None:
            file.page.update_date = ""
            generated += 1
            continue
        pages[f"{docs_dir.name}/{file.src_uri}"] = file.page

    dates = _source_dates(root)
    if dates is None:
        return env

    def read(path: str) -> str | None:
        candidate = root / path
        try:
            return candidate.read_text(encoding="utf8") if candidate.is_file() else None
        except OSError:
            return None

    resolved = newest_dates(pages, dates=dates, read=read)
    for path, date in resolved.items():
        pages[path].update_date = date

    _log.info(
        "sitemap <lastmod>: %d pages dated from git, %d left on the build date, "
        "%d generated pages with no date.",
        len(resolved),
        len(pages) - len(resolved),
        generated,
    )
    return env


def _one_line(value) -> str:
    """A frontmatter value as a single line, so it cannot break llms.txt's one-entry-per-line."""
    return " ".join(str(value).split())


def _required(meta, key: str, src_uri: str) -> str:
    value = meta.get(key)
    if not value or not str(value).strip():
        raise PluginError(
            f"'{src_uri}' is listed in the llmstxt sections but has no `{key}` in its "
            f"frontmatter. Every exported page needs a `title` and a `description`: together "
            f"they are the line that tells an assistant whether to read the page."
        )
    return _one_line(value)


def on_page_content(html, page, config, **kwargs):
    """Use the page's own `title` and `description` frontmatter for its llms.txt entry.

    Both halves fix the same class of problem — llms.txt taking its text from somewhere other
    than the page:

    * **The description** was the value written beside the path in mkdocs.yml, so the same
      sentence was maintained twice, and a glob entry could only carry *one* description for
      every page it matched — the 97 deployment guides all claimed to be the same page.
    * **The title** is `page.title`, which MkDocs resolves as *the nav label first*, falling back
      to the frontmatter `title` and then the first H1. Since 183 of this site's nav entries are
      labelled (`- Install: docs/.../install.md`), 180 entries were rendering as `[Install]`,
      `[Overview]` or `[Releases]` — labels that are perfectly clear next to their parent in a
      sidebar and say nothing at all in a flat list. The 66 that already looked right were the
      section-index and non-nav pages, where `page.title` had nothing to fall back *from*.

    This is a hook rather than a change to `plugin.config.sections` in `on_config` because by
    the time pages are rendered the plugin has already expanded the globs, and `page.meta` is
    the frontmatter as MkDocs parsed it — including anything the `meta` plugin injected from a
    directory-wide `.meta.yml`.

    Ordering is guaranteed, not lucky: `hooks` is validated after `plugins` and appended to the
    same collection, so a hook's handler for an event always runs after the plugins'. That is
    what lets this overwrite `_md_pages`, which the plugin fills in during *its* own
    `on_page_content`.
    """
    plugin = config["plugins"].get("llmstxt")
    if plugin is None:
        return None

    # Both are private, and both are read in the plugin's `on_post_build`:
    #   `_sections`  {section title: {src_uri: description}}, built in its `on_files`
    #   `_md_pages`  {src_uri: _MDPageInfo(title, path_md, md_url, content)}, built in its
    #                `on_page_content`
    # Assert their shape rather than skipping quietly: a plugin upgrade that renames either must
    # fail the build, not silently publish an llms.txt full of nav labels and no descriptions.
    sections = getattr(plugin, "_sections", None)
    exported = getattr(plugin, "_md_pages", None)
    if not isinstance(sections, dict) or not isinstance(exported, dict):
        raise PluginError(
            "mkdocs-llmstxt no longer exposes `_sections` and `_md_pages`, so llms.txt entries "
            "cannot be taken from the pages. Update publish-tool/mkdocs_hook.py to the new API."
        )

    src_uri = page.file.src_uri
    listed = [pages for pages in sections.values() if src_uri in pages]
    if not listed:
        return None

    meta = page.meta or {}
    title = _required(meta, "title", src_uri)
    description = _required(meta, "description", src_uri)

    for pages in listed:
        pages[src_uri] = description

    info = exported.get(src_uri)
    if info is None:  # pragma: no cover - the plugin records every page it selected
        raise PluginError(
            f"mkdocs-llmstxt selected '{src_uri}' but did not record it, so its llms.txt title "
            "would keep the nav label. Update publish-tool/mkdocs_hook.py to the new API."
        )
    exported[src_uri] = info._replace(title=title)
    return None
