"""Tree-dependent redirect expansion: the scanner, the three filters, and the four kinds.

The resolvers are pure over a `TreeIndex`, so most tests build one by hand; `scan_tree` gets
its own section against a real directory. What matters everywhere is the three filters — never
shadow a real page, never redirect into a 404, never chain — because they are what makes it
safe to materialise an expansion as files.
"""

from __future__ import annotations

import pytest

from ovweb.config import parse_site_config
from ovweb.expand import (
    TreeIndex,
    alias_entries,
    collapse,
    expand_alias,
    expand_candidate_paths,
    expand_for_version,
    expand_mirror,
    scan_tree,
    version_redirects,
    wipe_owned,
    with_stubs,
)
from ovweb.redirects import RedirectError, render_redirect, resolve_file_redirects

LAYOUT = {
    "site_url": "https://openvidu.io",
    "versioned_pages": ["docs", "meet"],
    "non_versioned_pages": ["pricing"],
    "assets": ["assets"],
    "pinned_assets": ["assets"],
    "root_files": ["index.html"],
    "feeds": [],
}


def build(*expand, files=()):
    return parse_site_config(
        {
            "schema": 2,
            "layout": LAYOUT,
            "redirects": {"files": list(files), "expand": list(expand)},
        },
        source="<test>",
    )


def index(*pages, stubs=None):
    """A TreeIndex from page paths and `{stub path: resolved target}`."""
    stubs = stubs or {}
    return TreeIndex(pages=frozenset((*pages, *stubs)), stub_targets=stubs)


CROSS_PRODUCT = {
    "id": "moved-provider-index",
    "kind": "cross-product",
    "at": "{version}/docs/self-hosting/{edition}/{provider}/index.html",
    "to": "install/",
    "canonical": "{site_url}/latest/docs/self-hosting/{edition}/{provider}/install/",
    "body": "Redirecting to the {edition} installation guide…",
    "values": {"edition": ["single-node", "ha"], "provider": ["aws", "on-premises"]},
}


# -- collapse ------------------------------------------------------------------------------


def test_a_plain_target_is_its_own_destination():
    assert collapse(index("3.8/docs/x/index.html"), "3.8/docs/x/") == "3.8/docs/x/"


def test_a_target_that_is_a_stub_is_followed():
    tree = index(stubs={"3.8/docs/old/index.html": "3.8/docs/new/"})
    assert collapse(tree, "3.8/docs/old/") == "3.8/docs/new/"


def test_a_chain_of_stubs_is_followed_to_the_end():
    tree = index(
        stubs={
            "3.8/docs/a/index.html": "3.8/docs/b/",
            "3.8/docs/b/index.html": "3.8/docs/c/",
        }
    )
    assert collapse(tree, "3.8/docs/a/") == "3.8/docs/c/"


def test_a_hops_own_fragment_replaces_the_incoming_one():
    """Matching the rendered JavaScript: the stub's fragment wins over the visitor's."""
    tree = index(stubs={"3.8/docs/faq/index.html": "3.8/docs/how-to/#backup"})
    assert collapse(tree, "3.8/docs/faq/") == "3.8/docs/how-to/#backup"
    assert collapse(tree, "3.8/docs/faq/#old-anchor") == "3.8/docs/how-to/#backup"


def test_a_fragment_survives_a_hop_that_has_none():
    tree = index(stubs={"3.8/docs/faq/index.html": "3.8/docs/how-to/"})
    assert collapse(tree, "3.8/docs/faq/#keep") == "3.8/docs/how-to/#keep"


def test_a_cycle_terminates():
    tree = index(
        stubs={
            "3.8/docs/a/index.html": "3.8/docs/b/",
            "3.8/docs/b/index.html": "3.8/docs/a/",
        }
    )
    assert collapse(tree, "3.8/docs/a/").startswith("3.8/docs/")


# -- scan_tree -----------------------------------------------------------------------------


def stub_page(target: str) -> str:
    return (
        '<!-- Generated by ovweb from the "x" rule -->'
        f'<meta http-equiv="refresh" content="0; url={target}">'
    )


def test_scan_indexes_pages_and_resolves_stub_targets(tmp_path):
    (tmp_path / "3.8" / "docs" / "real").mkdir(parents=True)
    (tmp_path / "3.8" / "docs" / "real" / "index.html").write_text("<html>page</html>")
    (tmp_path / "3.8" / "docs" / "gone").mkdir()
    (tmp_path / "3.8" / "docs" / "gone" / "index.html").write_text(stub_page("../real/#part"))

    scanned = scan_tree(tmp_path, ("3.8",))

    assert scanned.pages == {"3.8/docs/real/index.html", "3.8/docs/gone/index.html"}
    assert scanned.stub_targets == {"3.8/docs/gone/index.html": "3.8/docs/real/#part"}


def test_scan_skips_symlinks_and_other_prefixes(tmp_path):
    (tmp_path / "3.8" / "docs").mkdir(parents=True)
    (tmp_path / "3.8" / "docs" / "index.html").write_text("x")
    (tmp_path / "3.7" / "docs").mkdir(parents=True)
    (tmp_path / "3.7" / "docs" / "index.html").write_text("x")
    (tmp_path / "latest").symlink_to("3.8")

    scanned = scan_tree(tmp_path, ("3.8", "latest", "missing"))

    assert scanned.pages == {"3.8/docs/index.html"}


def test_scan_resolves_an_absolute_stub_target(tmp_path):
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "index.html").write_text(stub_page("/latest/docs/"))

    scanned = scan_tree(tmp_path, ("docs",))

    assert scanned.stub_targets == {"docs/index.html": "latest/docs/"}


def test_scan_drops_a_target_that_escapes_the_tree(tmp_path):
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "index.html").write_text(stub_page("../../outside/"))

    scanned = scan_tree(tmp_path, ("docs",))

    assert scanned.stub_targets == {}


# -- cross-product -------------------------------------------------------------------------


def cross(config, version, tree):
    return {r.path: r for r in expand_for_version(config, version, tree)}


def test_a_combination_with_a_live_target_becomes_a_stub():
    tree = index("3.8/docs/self-hosting/single-node/aws/install/index.html")
    resolved = cross(build(CROSS_PRODUCT), "3.8", tree)

    stub = resolved["3.8/docs/self-hosting/single-node/aws/index.html"]
    assert stub.to == "install/"
    assert stub.canonical == "https://openvidu.io/latest/docs/self-hosting/single-node/aws/install/"
    assert stub.body == "Redirecting to the single-node installation guide…"
    assert stub.relative is True


def test_a_real_page_at_the_old_path_is_never_shadowed():
    """ha/on-premises/ is still a real page, with no exclusion list to maintain."""
    tree = index(
        "3.8/docs/self-hosting/ha/on-premises/index.html",
        "3.8/docs/self-hosting/ha/aws/install/index.html",
    )
    resolved = cross(build(CROSS_PRODUCT), "3.8", tree)

    assert "3.8/docs/self-hosting/ha/on-premises/index.html" not in resolved
    assert "3.8/docs/self-hosting/ha/aws/index.html" in resolved


def test_a_combination_without_its_target_produces_no_stub():
    """No install guide, no redirect: a stub into a 404 is worse than the 404."""
    tree = index("3.8/docs/self-hosting/single-node/aws/install/index.html")
    resolved = cross(build(CROSS_PRODUCT), "3.8", tree)

    assert len(resolved) == 1  # the other three combinations have no install/ page


def test_the_version_gate_excludes_older_versions_outright():
    tree = index("3.7/docs/self-hosting/single-node/aws/install/index.html")
    gated = build({**CROSS_PRODUCT, "versions": ">=3.8"})

    assert cross(gated, "3.7", tree) == {}


def test_a_target_that_is_a_stub_is_collapsed():
    """The emitted target is the final destination, not the intermediate hop."""
    tree = index(
        "3.8/docs/self-hosting/single-node/upgrade/index.html",
        stubs={
            "3.8/docs/self-hosting/single-node/aws/install/index.html": (
                "3.8/docs/self-hosting/single-node/upgrade/"
            )
        },
    )
    resolved = cross(build(CROSS_PRODUCT), "3.8", tree)

    stub = resolved["3.8/docs/self-hosting/single-node/aws/index.html"]
    assert stub.to == "../upgrade/"


def test_an_existing_generated_stub_at_the_old_path_is_regenerated():
    tree = index(
        "3.8/docs/self-hosting/single-node/aws/install/index.html",
        stubs={"3.8/docs/self-hosting/single-node/aws/index.html": "3.8/docs/"},
    )
    resolved = cross(build(CROSS_PRODUCT), "3.8", tree)

    assert "3.8/docs/self-hosting/single-node/aws/index.html" in resolved


def test_candidate_paths_are_knowable_without_a_tree():
    config = build(CROSS_PRODUCT)
    assert len(expand_candidate_paths(config, "3.8")) == 4
    assert expand_candidate_paths(build({**CROSS_PRODUCT, "versions": ">=3.8"}), "3.7") == {}


# -- tree-rename ---------------------------------------------------------------------------

RENAME = {
    "id": "self-hosting-becomes-deployment",
    "kind": "tree-rename",
    "from": "{version}/docs/self-hosting",
    "to": "{version}/docs/deployment",
}


def test_every_page_under_the_new_path_gets_a_stub_at_its_old_path():
    tree = index(
        "3.9/docs/deployment/index.html",
        "3.9/docs/deployment/single-node/aws/install/index.html",
    )
    resolved = cross(build(RENAME), "3.9", tree)

    root = resolved["3.9/docs/self-hosting/index.html"]
    assert root.to == "../deployment/"
    assert root.canonical == "https://openvidu.io/latest/docs/deployment/"

    deep = resolved["3.9/docs/self-hosting/single-node/aws/install/index.html"]
    assert deep.to == "../../../../deployment/single-node/aws/install/"


def test_a_file_url_is_renamed_as_a_file():
    """reference-docs pages are plain .html files, not directory URLs."""
    tree = index("3.9/docs/deployment/reference/Foo.html")
    resolved = cross(build(RENAME), "3.9", tree)

    stub = resolved["3.9/docs/self-hosting/reference/Foo.html"]
    assert stub.to == "../../deployment/reference/Foo.html"


def test_a_stub_under_the_new_path_is_collapsed_not_copied():
    tree = index(
        "3.9/docs/deployment/index.html",
        stubs={"3.9/docs/deployment/faq/index.html": "3.9/docs/deployment/#help"},
    )
    resolved = cross(build(RENAME), "3.9", tree)

    assert resolved["3.9/docs/self-hosting/faq/index.html"].to == "../../deployment/#help"


def test_a_page_surviving_at_the_old_path_is_left_alone():
    tree = index(
        "3.9/docs/deployment/x/index.html",
        "3.9/docs/self-hosting/x/index.html",
    )
    resolved = cross(build(RENAME), "3.9", tree)

    assert resolved == {}


# -- version-alias -------------------------------------------------------------------------

ALIAS_RULE = {"id": "legacy", "kind": "version-alias", "folders": ["3.4.1", "3.0.0-beta1"]}


def test_folders_map_to_their_minor():
    entries = alias_entries(build(ALIAS_RULE))
    assert [(folder, minor) for _, folder, minor in entries] == [
        ("3.4.1", "3.4"),
        ("3.0.0-beta1", "3.0"),
    ]


def test_every_page_of_the_minor_is_aliased_with_an_absolute_target():
    config = build(ALIAS_RULE)
    rule, folder, minor = alias_entries(config)[0]
    tree = index("3.4/docs/x/index.html", "3.4/docs/reference/Foo.html")

    resolved = {r.path: r for r in expand_alias(config, rule, folder, minor, tree)}

    page = resolved["3.4.1/docs/x/index.html"]
    assert page.to == "/3.4/docs/x/"
    assert page.canonical == "https://openvidu.io/3.4/docs/x/"
    assert page.relative is False
    assert resolved["3.4.1/docs/reference/Foo.html"].to == "/3.4/docs/reference/Foo.html"


def test_the_minors_own_stubs_are_collapsed():
    """The version root is itself a stub, so /3.4.1/ points straight into the docs."""
    config = build(ALIAS_RULE)
    rule, folder, minor = alias_entries(config)[0]
    tree = index(
        "3.4/docs/index.html",
        stubs={"3.4/index.html": "3.4/docs/"},
    )

    resolved = {r.path: r for r in expand_alias(config, rule, folder, minor, tree)}

    assert resolved["3.4.1/index.html"].to == "/3.4/docs/"


# -- unversioned-mirror --------------------------------------------------------------------

MIRROR = {"id": "unversioned", "kind": "unversioned-mirror", "for_each": "versioned_pages"}


def mirrored(tree, config=None):
    config = config or build(MIRROR)
    return {r.path: r for r in expand_mirror(config, "3.8", tree)}


def test_every_page_answers_at_its_unversioned_path():
    resolved = mirrored(index("3.8/docs/index.html", "3.8/meet/embedded/index.html"))

    assert resolved["docs/index.html"].to == "/latest/docs/"
    assert resolved["docs/index.html"].canonical == "https://openvidu.io/latest/docs/"
    assert resolved["meet/embedded/index.html"].to == "/latest/meet/embedded/"


def test_a_file_url_is_mirrored_at_its_exact_path():
    """The exported reference-docs pages, which the sitemap-based mirror could not cover."""
    resolved = mirrored(index("3.8/docs/reference-docs/classes/Foo.html"))

    stub = resolved["docs/reference-docs/classes/Foo.html"]
    assert stub.to == "/latest/docs/reference-docs/classes/Foo.html"


def test_a_versioned_stub_is_mirrored_as_its_final_destination():
    """A renamed page's unversioned URL redirects once, not through a chain."""
    resolved = mirrored(
        index(
            "3.8/docs/how-to/index.html",
            stubs={"3.8/docs/faq/index.html": "3.8/docs/how-to/#backup"},
        )
    )

    assert resolved["docs/faq/index.html"].to == "/latest/docs/how-to/#backup"
    assert resolved["docs/faq/index.html"].canonical == "https://openvidu.io/latest/docs/how-to/"


def test_a_stub_leaving_the_version_folder_is_not_mirrored():
    resolved = mirrored(index(stubs={"3.8/docs/old/index.html": "pricing/"}))
    assert resolved == {}


# -- orchestration over a real tree ----------------------------------------------------------


def write_page(root, path, content="<html>page</html>"):
    file = root / path
    file.parent.mkdir(parents=True, exist_ok=True)
    file.write_text(content, encoding="utf-8")


def test_version_redirects_collapse_through_the_files_rules_of_the_same_run(tmp_path):
    """A files rule that stubs a cross-product target is applied before the expansion reads it."""
    config = build(
        CROSS_PRODUCT,
        files=[
            {
                "id": "moved-install",
                "at": "{version}/docs/self-hosting/single-node/aws/install/index.html",
                "to": "../setup/",
            }
        ],
    )
    write_page(tmp_path, "3.8/docs/self-hosting/single-node/aws/setup/index.html")
    write_page(tmp_path, "3.8/docs/self-hosting/single-node/aws/install/index.html")

    resolved = {r.path: r for r in version_redirects(tmp_path, config, "3.8")}

    assert resolved["3.8/docs/self-hosting/single-node/aws/index.html"].to == "setup/"


def test_two_rules_claiming_one_path_is_an_error(tmp_path):
    config = build(
        CROSS_PRODUCT,
        files=[
            {
                "id": "hand-written",
                "at": "{version}/docs/self-hosting/single-node/aws/index.html",
                "to": "../",
            }
        ],
    )
    write_page(tmp_path, "3.8/docs/self-hosting/single-node/aws/install/index.html")
    write_page(tmp_path, "3.8/docs/self-hosting/index.html")

    with pytest.raises(RedirectError, match="both generate"):
        version_redirects(tmp_path, config, "3.8")


def test_wipe_owned_refuses_a_directory_holding_content(tmp_path):
    config = build(CROSS_PRODUCT)
    stub = resolve_file_redirects(
        build(files=[{"id": "r", "at": "docs/index.html", "to": "x/", "relative": False}]),
        "3.8",
    )
    del config
    write_page(tmp_path, "docs/gone/index.html", render_redirect(stub[0]))
    write_page(tmp_path, "docs/real/index.html")

    with pytest.raises(RedirectError, match="not generated by ovweb"):
        wipe_owned(tmp_path / "docs")
    assert (tmp_path / "docs" / "real" / "index.html").exists()


def test_wipe_owned_removes_a_directory_of_stubs(tmp_path):
    stub = resolve_file_redirects(
        build(files=[{"id": "r", "at": "docs/index.html", "to": "x/", "relative": False}]),
        "3.8",
    )
    write_page(tmp_path, "docs/gone/index.html", render_redirect(stub[0]))

    assert wipe_owned(tmp_path / "docs") is True
    assert not (tmp_path / "docs").exists()
    assert wipe_owned(tmp_path / "docs") is False


def test_with_stubs_projects_unwritten_redirects_into_the_index():
    base = index("3.8/docs/target/index.html")
    files = resolve_file_redirects(
        build(files=[{"id": "r", "at": "{version}/docs/old/index.html", "to": "../target/"}]),
        "3.8",
    )
    projected = with_stubs(base, files)

    assert "3.8/docs/old/index.html" in projected.pages
    assert collapse(projected, "3.8/docs/old/") == "3.8/docs/target/"
