"""Resolve the single-page (`files`) redirect rules and render any redirect to HTML.

The tree-dependent expansion kinds build on this module; see :mod:`ovweb.expand`. Pure apart
from :func:`is_generated_redirect`.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

from .model import (
    VERSION_ROOT,
    RedirectOverride,
    RedirectRule,
    ResolvedRedirect,
    SiteConfig,
)
from .versions import matches

TEMPLATE_NAME = "redirect.html.j2"

#: The alias the mirror sends visitors to, and the prefix `promote_root_sitemap` writes into
#: every versioned URL.
ALIAS = "latest"

#: Emitted by the template into every page ovweb generates. Recognising one is what lets the
#: pipeline refuse to post-process a tree twice, and lets `ovweb verify` tell a generated stub
#: from a real page.
GENERATED_MARKER = "Generated by ovweb"

#: How much of a file has to be read to find the marker comment, which the template puts on
#: line 2.
MARKER_BYTES = 512

#: A generated redirect page is around 2 KB and a real page carries the theme chrome, so this
#: skips most of a tree before the marker check decides what is actually a redirect.
REDIRECT_MAX_BYTES = 8192

#: The destination a generated page redirects to, as written into its meta refresh.
REFRESH_TARGET = re.compile(r'http-equiv="refresh" content="0; *url=([^"]+)"')

# A target ends up in an HTML attribute, in a `meta refresh` content value and in a JavaScript
# string. Rejecting these characters outright is simpler than escaping the same value three
# different ways.
_FORBIDDEN_IN_TARGET = re.compile(r'["\'<>\s]')


class RedirectError(Exception):
    """A redirect rule cannot be resolved."""


def is_generated_redirect(path: Path, *, rule_id: str | None = None) -> bool:
    """Whether `path` is a redirect page ovweb generated, optionally from a given rule.

    Reads only the head of the file, so it is cheap enough to run over a whole tree.
    """
    try:
        head = path.read_bytes()[:MARKER_BYTES].decode("utf-8", errors="replace")
    except OSError:
        return False
    return GENERATED_MARKER in head and (rule_id is None or rule_id in head)


def resolve_file_redirects(config: SiteConfig, version: str) -> tuple[ResolvedRedirect, ...]:
    """Every file redirect that applies to `version`, fully resolved."""
    resolved = []
    for rule in config.file_rules:
        outcome = resolve_rule(config, rule, version)
        if outcome is not None:
            resolved.append(outcome)
    return tuple(resolved)


def resolve_rule(config: SiteConfig, rule: RedirectRule, version: str) -> ResolvedRedirect | None:
    """Resolve one rule for one version, or `None` when it does not apply."""
    if rule.versions is not None and not matches(rule.versions, version):
        return None

    override = _matching_override(rule, version)

    def pick(name: str):
        if override is not None:
            value = getattr(override, name)
            if value is not None:
                return value
        value = getattr(rule, name)
        if value is not None:
            return value
        return getattr(config.defaults, name, None)

    if not bool(pick("enabled")):
        return None

    path = _resolve_path(rule, version)
    relative = bool(pick("relative"))
    target = _interpolate(str(pick("to")), version=version, layout_url=config.layout.base_url)
    canonical_raw = pick("canonical")
    canonical = (
        _interpolate(str(canonical_raw), version=version, layout_url=config.layout.base_url)
        if canonical_raw
        else None
    )

    _validate_target(rule.id, target, relative=relative)
    if canonical is not None and not canonical.startswith(("http://", "https://")):
        raise RedirectError(
            f"redirect {rule.id!r}: canonical must be an absolute URL, got {canonical!r}"
        )

    return ResolvedRedirect(
        rule_id=rule.id,
        path=path,
        to=target,
        canonical=canonical,
        title=str(pick("title")),
        body=str(pick("body")),
        robots=str(pick("robots")),
        lang=str(pick("lang")),
        relative=relative,
        preserve_query_and_hash=bool(pick("preserve_query_and_hash")),
    )


def _matching_override(rule: RedirectRule, version: str) -> RedirectOverride | None:
    hits = [entry for entry in rule.when if matches(entry.versions, version)]
    if len(hits) > 1:
        raise RedirectError(
            f"redirect {rule.id!r} is ambiguous for version {version}: "
            f"{len(hits)} 'when' entries match ({', '.join(hit.versions for hit in hits)}). "
            "Version ranges must not overlap — a first-match-wins rule would make the "
            "published redirect depend on the order of the config file."
        )
    return hits[0] if hits else None


def _resolve_path(rule: RedirectRule, version: str) -> str:
    if rule.at == VERSION_ROOT:
        return f"{version}/index.html"
    if "{version}" not in rule.at:
        return rule.at
    return rule.at.replace("{version}", version)


def _interpolate(value: str, *, version: str, layout_url: str) -> str:
    return value.replace("{version}", version).replace("{site_url}", layout_url)


def _validate_target(rule_id: str, target: str, *, relative: bool) -> None:
    if not target:
        raise RedirectError(f"redirect {rule_id!r}: 'to' must not be empty")
    if _FORBIDDEN_IN_TARGET.search(target):
        raise RedirectError(
            f"redirect {rule_id!r}: 'to' must not contain quotes, angle brackets or "
            f"whitespace, got {target!r}"
        )
    if relative and target.startswith("/"):
        raise RedirectError(
            f"redirect {rule_id!r}: 'to' is {target!r}, but the rule is relative. A redirect "
            "installed inside a version folder must use a relative target: `latest` is a "
            "symlink to the newest version folder, so the same file answers at /latest/ and "
            "at /X.Y/, and an absolute target would leak a version number to visitors of the "
            "stable /latest/ URL. Set `relative: false` if the target really is site-absolute."
        )


def render_redirect(redirect: ResolvedRedirect) -> str:
    """Render one resolved redirect to an HTML page, newline-terminated.

    The template explains what each element in the page is for.
    """
    template = _environment().get_template(TEMPLATE_NAME)
    rendered = template.render(
        lang=redirect.lang,
        robots=redirect.robots,
        title=redirect.title,
        body=redirect.body,
        to=redirect.to,
        to_js=json.dumps(redirect.to),
        relative=redirect.relative,
        canonical=redirect.canonical,
        preserve_query_and_hash=redirect.preserve_query_and_hash,
        rule_id=redirect.rule_id,
    )
    return rendered if rendered.endswith("\n") else rendered + "\n"


@lru_cache(maxsize=1)
def _environment():
    from jinja2 import Environment, PackageLoader, select_autoescape

    return Environment(
        loader=PackageLoader("ovweb", "data/templates"),
        autoescape=select_autoescape(default_for_string=True, default=True),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
