"""Post-process a built gh-pages tree.

Port of `updateWebsite` from push-new-version.sh, with one deliberate structural change: it
takes the tree to work on as an argument and touches git only in the final step. That is what
makes `ovweb postprocess --tree <copy> --no-commit` a deterministic unit, and it is how the
parity gate compares this implementation against the shell one.

The step order is the shell's, preserved exactly. Where a step's behaviour differs, the
docstring says so and the parity gate allow-lists it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .. import fsops
from ..config import SiteConfig
from ..redirects import render_redirect, resolve_file_redirects
from ..releases import DestinationRegionError, splice_releases
from ..report import Reporter
from ..rewrite import (
    promote_root_sitemap,
    rewrite_404,
    rewrite_feed,
    rewrite_llms_txt,
    rewrite_non_versioned_file,
    rewrite_search_index,
    rewrite_versioned_file,
)
from ..versions import read_versions_json

#: Present in every redirect page ovweb writes. Used to recognise a tree that has already
#: been post-processed, because running the pipeline twice is not safe (see `_guard`).
GENERATED_MARKER = "Generated by ovweb"

SITEMAP = "sitemap.xml"
SEARCH_INDEX = "search/search_index.json"
LLMS_TXT = "llms.txt"


class PostprocessError(Exception):
    """The tree cannot be post-processed."""


@dataclass
class PostprocessResult:
    version: str
    update_latest: bool
    counts: dict[str, int] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    redirects_written: list[str] = field(default_factory=list)


def postprocess(
    tree: Path,
    *,
    config: SiteConfig,
    version: str,
    update_latest: bool,
    report: Reporter,
    force: bool = False,
) -> PostprocessResult:
    """Turn mike's raw output for `version` into the published site layout."""
    layout = config.layout
    version_dir = tree / version
    if not version_dir.is_dir():
        raise PostprocessError(
            f"{version_dir} does not exist. mike should have created it — has the deploy run?"
        )

    redirects = resolve_file_redirects(config, version)
    result = PostprocessResult(version=version, update_latest=update_latest)

    _guard(version_dir, force=force)

    # 1. Drop what must never be published.
    report.step("remove-overrides", "Remove the theme override folder")
    removed = fsops.remove(version_dir / "overrides", required=False)
    # `site/` only exists when the tree came from a checkout rather than a fresh worktree.
    removed += fsops.remove(tree / "site", required=False)
    report.result("remove-overrides", removed=int(removed))

    # 2. Versioned pages: pin assets, absolutise root links, consolidate SEO URLs.
    report.step("rewrite-versioned", "Rewrite links in versioned pages")
    changed = 0
    for directory in layout.versioned_pages:
        changed += fsops.rewrite_tree(
            version_dir / directory,
            lambda text: rewrite_versioned_file(text, version=version, layout=layout),
        )
    result.counts["rewrite-versioned"] = changed
    report.result("rewrite-versioned", files_changed=changed)

    # 3. Search index: relative locations become absolute.
    report.step("rewrite-search-index", "Absolutise the search index locations")
    changed = int(
        fsops.rewrite_single(
            version_dir / SEARCH_INDEX,
            lambda text: rewrite_search_index(text, version=version, layout=layout),
        )
    )
    result.counts["rewrite-search-index"] = changed
    report.result("rewrite-search-index", files_changed=changed)

    if update_latest:
        _rewrite_promoted_pages(tree, version=version, config=config, report=report, result=result)
        _promote_to_root(tree, version=version, config=config, report=report, result=result)
    else:
        _strip_promoted_pages(tree, version=version, config=config, report=report, result=result)

    # 7. The generated redirects.
    report.step("install-redirects", "Write the generated redirect pages")
    for redirect in redirects:
        fsops.write_text(tree / redirect.path, render_redirect(redirect))
        result.redirects_written.append(redirect.path)
        report.detail(f"{redirect.path} -> {redirect.to} [{redirect.rule_id}]")
    report.result("install-redirects", written=len(result.redirects_written))

    # 8/9. Sitemaps.
    if update_latest:
        _promote_sitemap(tree, version=version, config=config, report=report, result=result)
    _remove_version_sitemap(tree, version=version, report=report, result=result)

    # 10. The releases pages must show the newest notes in every version.
    _sync_releases(tree, version=version, config=config, report=report, result=result)

    return result


def _guard(version_dir: Path, *, force: bool) -> None:
    """Refuse to post-process a tree that has already been post-processed.

    The pipeline is not idempotent, and a second run is silently destructive in two ways:
    the sentinel that shields author-pinned `/X.Y/docs/` links is single-shot, so a re-run
    strips the version out of every release-notes link in the blog; and promotion moves
    directories, so it half-fails once they are gone. The shell had no guard at all.
    """
    index = version_dir / "index.html"
    if not index.is_file():
        return
    try:
        head = index.read_bytes()[:512].decode("utf-8", errors="replace")
    except OSError:  # pragma: no cover - unreadable file surfaces later anyway
        return
    if GENERATED_MARKER in head and not force:
        raise PostprocessError(
            f"{index} is already a generated redirect, so this tree has been post-processed "
            "before. Running the pipeline twice would strip the version out of author-pinned "
            "links and fail on the already-moved directories. Re-deploy the version with mike "
            "first, or pass --force if you know the tree is safe."
        )


def _rewrite_promoted_pages(
    tree: Path, *, version: str, config: SiteConfig, report: Reporter, result: PostprocessResult
) -> None:
    """Rewrite the pages that are about to be served from the site root."""
    layout = config.layout
    version_dir = tree / version
    report.step("rewrite-non-versioned", "Rewrite links in pages promoted to the root")

    changed = int(
        fsops.rewrite_single(
            version_dir / "404.html",
            lambda text: rewrite_404(text, version=version, layout=layout),
        )
    )

    def promote(text: str) -> str:
        return rewrite_non_versioned_file(text, version=version, layout=layout)

    for directory in layout.non_versioned_pages:
        changed += fsops.rewrite_tree(version_dir / directory, promote)
    changed += int(fsops.rewrite_single(version_dir / "index.html", promote))

    changed += int(
        fsops.rewrite_single(
            version_dir / LLMS_TXT,
            lambda text: rewrite_llms_txt(text, version=version, layout=layout),
            required=False,
        )
    )

    for feed in layout.feeds:
        changed += int(
            fsops.rewrite_single(
                version_dir / feed,
                lambda text: rewrite_feed(text, version=version),
                required=False,
            )
        )

    result.counts["rewrite-non-versioned"] = changed
    report.result("rewrite-non-versioned", files_changed=changed)


def _promote_to_root(
    tree: Path, *, version: str, config: SiteConfig, report: Reporter, result: PostprocessResult
) -> None:
    """Move this version's root-served content out to the site root.

    Assets are **copied**, not moved: the version folder keeps its own copy, which is what
    the `/X.Y/assets/` pinning applied earlier relies on. Everything else is moved, so the
    version folder stops serving pages that belong to the root.
    """
    layout = config.layout
    version_dir = tree / version
    report.step("promote-to-root", "Promote assets, root files and non-versioned pages")

    for asset in layout.assets:
        _require_built(version_dir / asset, key="assets", name=asset, version=version)
        fsops.copy_tree(version_dir / asset, tree / asset)
    for name in layout.root_files:
        _require_built(version_dir / name, key="root_files", name=name, version=version)
        fsops.move(version_dir / name, tree / name)
    for page in layout.non_versioned_pages:
        _require_built(version_dir / page, key="non_versioned_pages", name=page, version=version)
        fsops.move(version_dir / page, tree / page)

    result.counts["promote-to-root"] = (
        len(layout.assets) + len(layout.root_files) + len(layout.non_versioned_pages)
    )
    report.result(
        "promote-to-root",
        assets_copied=len(layout.assets),
        files_moved=len(layout.root_files),
        pages_moved=len(layout.non_versioned_pages),
    )


def _require_built(path: Path, *, key: str, name: str, version: str) -> None:
    """Fail with the config key at fault rather than a bare FileNotFoundError.

    Promotion is strict on purpose — silently skipping a page the config asks for would publish
    a site missing it — but the overwhelmingly likely cause is a name in ovweb.yaml that does not
    match anything the site builds, so say that.
    """
    if path.exists():
        return
    raise PostprocessError(
        f"ovweb.yaml lists {name!r} under layout.{key}, but the build produced no "
        f"{version}/{name}. Either the name is wrong, or the page is not in the MkDocs nav."
    )


def _strip_promoted_pages(
    tree: Path, *, version: str, config: SiteConfig, report: Reporter, result: PostprocessResult
) -> None:
    """Delete the root-served content from a version folder without touching the root.

    Every removal is tolerant: an old version branch may never have built some of these
    files at all, because llms.txt and the RSS feeds need plugins its mkdocs.yml did not
    have. index.html is not removed here — the generated redirect overwrites it.
    """
    layout = config.layout
    version_dir = tree / version
    report.step("strip-non-versioned", "Delete the promoted pages from the version folder")

    removed = fsops.remove_all(
        (version_dir / page for page in layout.non_versioned_pages), required=False
    )
    removed += fsops.remove_all(
        (version_dir / name for name in layout.files_removed_from_past_version), required=False
    )

    result.counts["strip-non-versioned"] = removed
    report.result("strip-non-versioned", removed=removed)


def _promote_sitemap(
    tree: Path,
    *,
    version: str,
    config: SiteConfig,
    report: Reporter,
    result: PostprocessResult,
) -> None:
    """Copy the version's sitemap to the root and rewrite it for the root URL scheme.

    This is the only sitemap the site publishes; `robots.txt` names it, and it is a plain
    `urlset` rather than an index, so it has to list every URL itself.
    """
    report.step("promote-sitemap", "Copy the version sitemap to the root and rewrite it")

    source = tree / version / SITEMAP
    target = tree / SITEMAP
    text = promote_root_sitemap(fsops.read_text(source), version=version, layout=config.layout)
    fsops.write_text(target, text)
    fsops.write_gzip(target)

    result.counts["promote-sitemap"] = 1
    report.result("promote-sitemap", written=1)


def _remove_version_sitemap(
    tree: Path, *, version: str, report: Reporter, result: PostprocessResult
) -> None:
    """Delete this version's sitemap from the published tree.

    The shell pruned the root-served pages out of each version's sitemap so it would not
    advertise URLs that had moved to the root. But nothing ever consumed those files:
    `robots.txt` names only the root sitemap, that sitemap is a plain `urlset` rather than an
    index, and no page links to a version's copy. Maintaining them was work in service of
    nothing, so they are removed instead.

    Only the version being published is touched, in keeping with the rest of the pipeline: a
    publish's blast radius is its own folder, plus the release-notes splice. Versions published
    before this change keep their sitemap until they are next published; `ovweb verify` reports
    them, and a one-off cleanup can remove them without a rebuild.
    """
    report.step("remove-version-sitemap", "Remove this version's sitemap")

    removed = 0
    for name in (SITEMAP, f"{SITEMAP}.gz"):
        removed += fsops.remove(tree / version / name, required=False)

    result.counts["remove-version-sitemap"] = removed
    report.result("remove-version-sitemap", removed=removed)


def _sync_releases(
    tree: Path, *, version: str, config: SiteConfig, report: Reporter, result: PostprocessResult
) -> None:
    """Make every version's releases pages show the newest release notes.

    Publishing the newest version pushes its notes out to every other version folder;
    re-publishing an older version pulls the current newest notes back in, so a rebuild does
    not regress it to the notes that version shipped with.
    """
    report.step("sync-releases", "Splice the newest release notes across versions")

    if result.update_latest:
        pairs = [(version, other) for other in _published_versions(tree, report)]
    else:
        newest = _resolve_latest(tree, report)
        pairs = [] if newest is None else [(newest, version)]

    spliced = 0
    for source, destination in pairs:
        if source == destination:
            continue
        spliced += _splice_pair(
            tree,
            source=source,
            destination=destination,
            config=config,
            report=report,
            result=result,
        )

    result.counts["sync-releases"] = spliced
    report.result("sync-releases", pages_spliced=spliced)


def _splice_pair(
    tree: Path,
    *,
    source: str,
    destination: str,
    config: SiteConfig,
    report: Reporter,
    result: PostprocessResult,
) -> int:
    spliced = 0
    for page in config.layout.versioned_pages:
        source_file = tree / source / page / "releases" / "index.html"
        destination_file = tree / destination / page / "releases" / "index.html"
        # Only copy when both sides have this releases page: OpenVidu Meet's documentation
        # did not exist before 3.4.
        if not source_file.is_file() or not destination_file.is_file():
            continue
        try:
            outcome = splice_releases(
                fsops.read_text(source_file), fsops.read_text(destination_file)
            )
        except DestinationRegionError as error:
            # An old version folder may have been built by a theme version that named these
            # regions differently. Warn and leave it as built rather than aborting a publish
            # that is already half done. A problem in the *source* is fatal and propagates.
            message = f"could not splice release notes into {destination}/{page}: {error}"
            result.warnings.append(message)
            report.warn(f"{message} — left as built")
            continue
        fsops.write_text(destination_file, outcome.html)
        report.detail(
            f"{source}/{page} -> {destination}/{page}: "
            f"{outcome.article_bytes} bytes, {outcome.tocs_replaced} table(s) of contents"
        )
        spliced += 1
    return spliced


def _published_versions(tree: Path, report: Reporter) -> list[str]:
    path = tree / "versions.json"
    if not path.is_file():
        report.warn("versions.json not found; the release notes were not copied to other versions")
        return []
    return [entry.version for entry in read_versions_json(fsops.read_text(path))]


def _resolve_latest(tree: Path, report: Reporter) -> str | None:
    """Which version `latest` currently points at.

    mike materialises the alias as a symlink whose target is the version folder name, so the
    symlink is the authority. versions.json is the fallback for a non-symlink alias.
    """
    alias = tree / "latest"
    if alias.is_symlink():
        return Path(alias.readlink()).name

    versions = tree / "versions.json"
    if versions.is_file():
        from ..versions import alias_target

        target = alias_target(read_versions_json(fsops.read_text(versions)), "latest")
        if target:
            return target

    report.warn("could not resolve the 'latest' alias; the releases pages were left as built")
    return None
