name: Publish Web
on:
  workflow_dispatch:
    inputs:
      script:
        description: "Select the script to execute"
        required: true
        type: choice
        options:
          - push-new-version
          - overwrite-latest-version
          - overwrite-past-version
      version:
        description: "Version to publish"
        required: true
        type: string
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x
      - name: Install safe-chain
        uses: OpenVidu/actions/install-safe-chain@040cbfd01320475801d7b12e33769e0d55a737a8 # v1.0.21

      - name: Install dependencies
        run: |
          sudo apt-get update
          # We pin the version of pygments to avoid breaking <a> elements as code block titles
          pip install mike "mkdocs-material[imaging]==9.7.6" "pygments<2.20" mkdocs-glightbox mkdocs-llmstxt mkdocs-rss-plugin
          sudo apt-get install --fix-missing libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          sudo apt-get install -y --fix-missing pngquant

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Run selected script
        working-directory: ./custom-versioning
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          ./${{ github.event.inputs.script }}.sh ${{ github.event.inputs.version }}
